name: mainapp
description: A Flutter project for Computer Club.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  model_viewer_plus: ^1.7.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.1

dev_dependencies:
  widgetbook: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/twitter.html
  uses-material-design: true
